server {
    listen 80;
    server_name *.test;

    # Optionally redirect to HTTPS? 
    # For dev speed, maybe not mandatory, but good practice.
    # return 301 https://$host$request_uri;
    
    root {{SLD_RUNTIME_PATH}};
    error_log /var/log/nginx/sld-error.log;
    access_log /var/log/nginx/sld-access.log;

    location / {
        try_files /router.php =404;
        fastcgi_pass unix:/run/php/php-fpm.sock; 
        fastcgi_index router.php;
        fastcgi_param SCRIPT_FILENAME $document_root/router.php;
        include fastcgi_params;
        fastcgi_param HTTP_HOST $host;
    }
}

server {
    listen 443 ssl http2;
    server_name *.test;
    root {{SLD_RUNTIME_PATH}};

    ssl_certificate     /var/lib/sld/certs/dev.pem;
    ssl_certificate_key /var/lib/sld/certs/dev-key.pem;

    error_log /var/log/nginx/sld-error.log;
    access_log /var/log/nginx/sld-access.log;

    location / {
        try_files /router.php =404;
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_index router.php;
        fastcgi_param SCRIPT_FILENAME $document_root/router.php;
        include fastcgi_params;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param HTTPS on;
        fastcgi_param PHP_VALUE "error_reporting=E_ALL & ~E_DEPRECATED";
    }
}
